### ISSUE TITLE
Default object file format should be RT11.

### ISSUE THREAD

**Issue by AK6DN** [Rhialto/macro11#4] opened 2020-03-10 19:16 UTC
The default object file format should be RT11, not RSX11, as the original legacy version of this macro11 tool only supported RT11 format. Making RSX the default causes needless confusion.

**Comment by Rhialto** [comment] 2020-03-10 21:09
Hmmm you have a point. On the other hand, I've been following RSX documentation, in particular [this](http://www.bitsavers.org/pdf/dec/pdp11/rsx11/RSX11Mplus_V4.x/4a/AA-KX10A-TC_PDP-11_MACRO-11_Reference_Manual_May88.pdf)  to check its behaviour in case of doubt. I also have compared actual run-time behaviour with this version.

Maybe a compile-time default that is settable in the Makefile? Then we can both have our preference.

**Comment by AK6DN** [comment] 2020-03-10 22:08
I use [http://www.bitsavers.org/pdf/dec/pdp11/rt11/v5.6_Aug91/AA-PD6PA-TC_RT-11_Volume_and_File_Formats_Manual_Aug91.pdf](url) as a reference for obj2bin.pl as the object file specification, chapter 2. 

RT11 vs RSX11 object format really does not matter to me, I just added the -rt11 switch to my makefile. But my obj2bin.pl does not have the capability to process RSX .obj files, it only does RT11 format. So I'm thinking more of other users that just run 'macro11 foo.mac' and then feed the file to obj2bin.pl and it will barf, complaining about the object file format is illegal.

**Comment by AK6DN** [comment] 2020-03-11 05:36
Ok, I have released a new version (v2.1) of obj2bin.pl that now adds the capability to parse RSX11 format object files in addition to the existing capability of parsing RT11 format object files.

The default is to assume RSX11 format (as your macro11 does).
A "--rt11" option switch selects RT11 format object files.
A "--rsx11" option switch selects RSX11 format object files (but that is the default if --rt11 is absent).

I also changed the default output file format to be PDP-11 absolute binary records (BIN format).
Before you explicitly had to add the "--binary" option, now it assumes that by default.

**Comment by Rhialto** [comment] 2020-03-11 20:40
Hah! I was adding a compile time option for the object file format with RT11 as default (changeable in the Makefile), but I guess I'll leave it at RSX then. I realised it actually doesn't matter much for me which format it is by default. The regression tests with dumpobj don't even see the difference.

**Comment by AK6DN** [comment] 2020-03-11 21:23
Yup. dumpobj should not see an difference. The data in the .obj file should be exactly the same, just the header/trailers differ. RT11 format is a bit more robust with the header flag bytes and trailing checksum byte than is RSX11 format, but not enough to worry about. I just prefer that whatever the default flags/format of macro11 output be, then obj2bin.pl accepts that by default also. So we should be ok. I also set obj2bin.pl default output to be .bin files for loading direct into SIMH, etc.

I released a new obj2bin as v2.1. I don't know whether your subtree link will pick that up by default or you need to do something in your repo to cause it to happen.

Should be able to close this issue.

**Comment by Rhialto** [comment] 2020-03-11 22:00
The subtree link differs from submodules; I think for users who just clone a repository it is a bit easier since you get everything at once (for submodules I think you have to do an extra step). But at the cost that the linking repository must incorporate updates explicitly  every time an update is required (`git subtree pull --prefix obj2bin https://github.com/AK6DN/obj2bin.git master`), which I've just done.

I have also put a reference to the original in the README file, for better attribution, and for when the copied version might get out of date or something.

Thanks, and I'll close the issue with that.

**Closed by Rhialto** 2020-03-11 22:00 UTC
